# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 23:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170705_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_job',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 23, 59, 46, 419328), editable=False),
        ),
    ]
