# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20170705_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 0, 1, 54, 650669), editable=False),
        ),
    ]
