# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 00:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170706_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 0, 10, 10, 861878), editable=False),
        ),
    ]
