# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170706_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 12, 23, 7, 9, 508246), editable=False),
        ),
    ]
