# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 00:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20170712_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 13, 0, 14, 39, 464119), editable=False),
        ),
    ]
